accounts/urls.py
'''
Created on 15 sep 2013

@author: balp
'''

from django.conf.urls import patterns, url

from accounts import views

urlpatterns = patterns('',
    url(r'^profile/$', views.profile, name='profile'),
)

nuitradgarden/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'plants.views.IndexView', name='index'),
    url(r'^plants/', include('plants.urls', namespace="plants")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^accounts/login/$',  login),
    url(r'^accounts/logout/$', logout),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

plants/urls.py
'''
Created on 15 sep 2013

@author: balp
'''

from django.conf.urls import patterns, url

from plants import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
)

accounts/models.py
from django.db import models

# Create your models here.

plants/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Grupp(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    grupp = models.ForeignKey('self', blank=True, null=True, related_name='children')

class Sort(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    grupp = models.ForeignKey(Grupp)
    
class Plant(models.Model):
    sort = models.ForeignKey(Sort)
    user = models.ForeignKey(User)
    position = models.TextField()
    planted = models.DateField(blank=True, null=True)

users/models.py
from django.db import models

# Create your models here.

accounts/views.py
# Create your views here.
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def profile(request):
    context = { 'user': request.user }
    return render(request, 'accounts/profile.html', context)

plants/views.py
# Create your views here.
#from django.shortcuts import get_object_or_404, render
#from django.http import HttpResponseRedirect
#from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from plants.models import Plant


class IndexView(generic.ListView):
    template_name = 'plants/index.html'
    model = Plant
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)
    #def get_queryset(self, **kwargs):
    #    context = super(ArticleListView, self).get_context_data(**kwargs)
    #    return context


class DetailView(generic.DetailView):
    model = Plant
    template_name = 'plants/detail.html'
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DetailView, self).dispatch(*args, **kwargs)

users/views.py
# Create your views here.

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}

  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}

  
  <table class="userinfo">
  <thead>
  <tr><th class="username" colspan="2"> {{ user }} </th></tr>
  </thead>
  <tbody>
    
    
    <tr class="even_row"><th class="userheader">Username</th><td class="userinfo"> {{user.username }} </td></tr>
    <tr class="odd_row"><th class="userheader">Förnamn</th><td class="userinfo"> {{user.first_name }} </td></tr>
    <tr class="even_row"><th class="userheader">Efternamn</th><td class="userinfo"> {{user.last_name }} </td></tr>
    <tr class="odd_row"><th class="userheader">Epost</th><td class="userinfo"> {{user.email }} </td></tr>
    <tr class="even_row"><th class="userheader">Senast inloggad</th><td class="userinfo"> {{user.last_login }} </td></tr>
    <tr class="odd_row"><th class="userheader">Medlem sen</th><td class="userinfo"> {{user.date_joined }} </td></tr>
  </tbody>
  </table>
 
{% endblock %}

accounts/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static "style.css" %}" />
    <title>{% block title %}Nu i trädgården{% endblock %}</title>
</head>

<body>
    <div id="sidebar">
        {% block sidebar %}
        <ul class="sidebar">
            <li class="sidebar" class="odd_row"><a class="sidebar" href="/">Hem</a></li>
            <li class="sidebar" class="even_row"><a class="sidebar" href="/blog/">Blog</a></li>
            <li class="sidebar" class="odd_row"><a class="sidebar" href="/vaxter/">Växter</a></li>
        </ul>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

plants/templates/plants/detail.html
{% extends "base.html" %}

{% block content %}

  {% if form.errors %}
    <p class="error">Sorry, that's not a valid username or password</p>
  {% endif %}

  
  <table class="userinfo">
  <thead>
  <tr><th class="username" colspan="2"> {{ object.sort.name }} </th></tr>
  </thead>
  <tbody>
    
    <tr class="even_row"><th class="userheader">Var</th><td class="userinfo"> {{object.position }} </td></tr>
    <tr class="even_row"><th class="userheader">Planterad</th><td class="userinfo"> {{object.planted|date }} </td></tr>
    <tr class="even_row"><th class="userheader">Om</th><td class="userinfo"> {{object.sort.description }} </td></tr>
     </tbody>
  </table>
 
{% endblock %}

plants/templates/plants/index.html
{% extends "base.html" %}

{% block content %}

    <h2>Plator</h2>
    <table><tbody>
        {% for plant in object_list %}
            <tr>
                <td> {{ plant.planted.year }} </td>
                <td><a href="{% url 'plants:detail' plant.id %}">{{ plant.sort.name }}</a></td>
                <td>{{ plant.position }}</td>
            </tr>
        {% endfor %}
    </tbody></table>
 
{% endblock %}